# Generated by Django 5.0.4 on 2024-04-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='name_movie',
        ),
    ]
