# Generated by Django 5.0.4 on 2024-04-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_name_movie_name_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='tickets.guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie', to='tickets.movie'),
        ),
    ]
